allowBuilds:
  "@merqo/ui": true
  "@merqo/ui@https://codeload.github.com/cljiahao/merqo-ui/tar.gz/4aa48fdb482be3b8d519154eb0679f3d49bfcd42": true
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - sharp
  - "@merqo/ui"

overrides:
  sharp@<0.35.0: ">=0.35.0"
  postcss@<8.5.18: ">=8.5.18"
