allowBuilds:
  "@merqo/ui": true
  "@merqo/ui@https://codeload.github.com/cljiahao/merqo-ui/tar.gz/e88ea5dfb080c9bee78247aa4fc6e54c5add4ef0": true
  "@merqo/ui@https://codeload.github.com/cljiahao/merqo-ui/tar.gz/600d2241b4b2ea9325eb5985da818387c6e975af": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  "@merqo/ui@https://codeload.github.com/cljiahao/merqo-ui/tar.gz/982ab522ae058d9a65a219ced82d25b115b820a8": true
  "@merqo/ui@https://codeload.github.com/cljiahao/merqo-ui/tar.gz/b2bbbf757444c4cffcb206ae118aba5e100407dd": true
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - sharp
  - "@merqo/ui"

overrides:
  sharp@<0.35.0: ">=0.35.0"
  postcss@<8.5.23: ">=8.5.23"
  nanoid@<3.3.17: ">=3.3.17"
  undici@<7.29.0: ">=7.29.0 <8"
  fast-uri@<4.1.2: ">=4.1.2"
  js-yaml@<4.3.1: ">=4.3.1"
  brace-expansion@<1.1.17: ">=1.1.17 <2"
  brace-expansion@>=2.0.0 <2.1.2: ">=2.1.2 <3"
  brace-expansion@>=3.0.0 <5.0.9: ">=5.0.9"
